#!/usr/bin/python
'''
    Purpose: http://cryptopals.com/sets/1/challenges/1/
    @author:Pramod S   
'''
import binascii
import base64

def hextoBase64(string):
    binaryData = binascii.unhexlify(string)
    #print(binaryData)
    return base64.b64encode(binaryData).decode('ascii')

string = '49276d206b696c6c696e6720796f757220627261696e206c696b65206120706f69736f6e6f7573206d757368726f6f6d'
decode = hextoBase64(string)
print(decode)
    
